version: '3.8'

services:

  postgres:
    image: 'timescale/timescaledb-ha:pg14-latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
