version: '3.8'

services:

  kafka-broker:
    image: 'confluentinc/cp-kafka:7.0.1'
    hostname: 'kafka-broker'
    container_name: 'kafka-broker'
    ports:
      - '9092:9092'
      - '9101:9101'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: 'localhost'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-broker:29092,CONTROLLER://kafka-broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - './kafka/update_run.sh:/tmp/update_run.sh'
    command: "bash -c '/tmp/update_run.sh && /etc/confluent/docker/run'"

  kafka-schema-registry:
    image: 'confluentinc/cp-schema-registry:7.0.1'
    hostname: 'kafka-schema-registry'
    container_name: 'kafka-schema-registry'
    depends_on:
      - 'kafka-broker'
    ports:
      - '8084:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: 'kafka-schema-registry'
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka-broker:29092'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8081'

  druid:
    image: 'apache/druid:0.22.1'
    hostname: 'druid'
    container_name: 'druid'
    ports:
      - '8888:8888'
    command:
      - 'start-micro-quickstart'
