version: '3.8'
services:
  presto:
    image: 'prestosql/presto:latest'
    ports:
      - '8080:8080'
  sqlpad:
    image: 'sqlpad/sqlpad:latest'
    ports:
      - '80:3000'
    environment:
      SQLPAD_ADMIN: 'max@streese.com'
      SQLPAD_ADMIN_PASSWORD: 'max.admin'
